//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EipService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EipService.WS_FGS_VLTSoap")]
    public interface WS_FGS_VLTSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMD5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMD5Async(string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Vlt_No", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_Vlt_NoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_City", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_CityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_City_Place", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_City_PlaceAsync(string meb_zip_add_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_City_Place_Zip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_City_Place_ZipAsync(string meb_zip_add_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_City_Place_By_Zip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.Get_City_Place_By_ZipResponseGet_City_Place_By_ZipResult> Get_City_Place_By_ZipAsync(string MEB_ZIP_ADD_zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Vlt_Basic_Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_Vlt_Basic_DataAsync(
                    string bel_no, 
                    string ble_type, 
                    string userid, 
                    string password, 
                    string pass_question, 
                    string pass_answer, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Vlt_Basic_Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Update_Vlt_Basic_DataAsync(
                    string bel_no, 
                    string ble_type, 
                    string userid, 
                    string pass_question, 
                    string pass_answer, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Vlt_Basic_Data_Per", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Update_Vlt_Basic_Data_PerAsync(
                    string bel_no, 
                    string ble_type, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno, 
                    string job, 
                    string school, 
                    string icno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Vlt_Basic_Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_Basic_DataAsync(string bel_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vlt_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Vlt_LoginAsync(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Userid_Count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_Userid_CountAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Userid_Count_ByBleno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_Userid_Count_ByBlenoAsync(string bel_no, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BelNo_ByQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_BelNo_ByQuestionAsync(string userid, string email, string pass_question, string pass_answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Vlt_Password", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Update_Vlt_PasswordAsync(string bel_no, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_mail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_mailAsync(string ls_from, string ls_fname, string ls_to, string ls_toname, string ls_mserver, string ls_subject, string ls_body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_mail_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_mail_1Async(string ls_from, string ls_fname, string ls_to, string ls_toname, string ls_mserver, string ls_subject, string ls_body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_Mail_3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_Mail_3Async(string ls_to, string ls_to_name, string ls_f_name, string ls_subject, string ls_body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetPageAsync(string p_url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_PilNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_PilNoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Pilgrimage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_PilgrimageAsync(
                    string pil_no, 
                    string bel_no, 
                    string pil_type, 
                    string pil_mem_type, 
                    string pil_stay, 
                    string pil_date, 
                    string pil_num, 
                    string pil_stay_man_num, 
                    string pil_stay_woman_num, 
                    string pil_eat_num, 
                    string pil_eat_box, 
                    string bel_type, 
                    string pil_leader, 
                    string pil_htel, 
                    string pil_otel, 
                    string pil_mtel, 
                    string pil_state, 
                    string ls_dsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Pil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Update_PilAsync(
                    string pil_no, 
                    string bel_no, 
                    string pil_type, 
                    string pil_mem_type, 
                    string pil_stay, 
                    string pil_date, 
                    string pil_num, 
                    string pil_stay_man_num, 
                    string pil_stay_woman_num, 
                    string pil_eat_num, 
                    string pil_eat_box, 
                    string bel_type, 
                    string pil_leader, 
                    string pil_htel, 
                    string pil_otel, 
                    string pil_mtel, 
                    string pil_mass, 
                    string pil_mass_mtel, 
                    string pil_state, 
                    string user_no, 
                    string user_rec, 
                    string ls_dsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Pilgrimage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_PilgrimageAsync(string ser_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Pil_Mem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Pil_MemAsync(string pil_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Pil_Mem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_Pil_MemAsync(string pil_no, string seq_no, string pil_cname, string pil_sex, string pil_tel, string pil_addr, string pil_email, string pil_type, string pil_meno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Item_Source", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Item_SourceAsync(string item_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Vlt_Skill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_SkillAsync(string bel_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Vlt_Skill_By_Item_No", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Get_Vlt_Skill_By_Item_NoAsync(string bel_no, string item_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Vlt_Skill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_Vlt_SkillAsync(string bel_no, string item_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_Vlt_Skill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Del_Vlt_SkillAsync(string bel_no, string item_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Vlt_Type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_Vlt_TypeAsync(string bel_no, string mem_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Vlt_Type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_TypeAsync(string bel_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Mem_Ask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_Mem_AskAsync(string qu_no, string bel_no, string ask_title, string ask_content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Mem_Ask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Update_Mem_AskAsync(string ask_no, string res_user_no, string res_content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Bel_Ask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Bel_AskAsync(string bel_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_All_Bel_Ask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_All_Bel_AskAsync(string Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_tbMessageInform1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Add_tbMessageInform1Async(string SEQNo, string Memo1, string TransactionAmount, string TransactionDate, string TransactionTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRandomValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRandomValidateAsync(int len);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Get_City_Place_By_ZipResponseGet_City_Place_By_ZipResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface WS_FGS_VLTSoapChannel : EipService.WS_FGS_VLTSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class WS_FGS_VLTSoapClient : System.ServiceModel.ClientBase<EipService.WS_FGS_VLTSoap>, EipService.WS_FGS_VLTSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_FGS_VLTSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_FGS_VLTSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_FGS_VLTSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FGS_VLTSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_FGS_VLTSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FGS_VLTSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_FGS_VLTSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_FGS_VLTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetMD5Async(string Source)
        {
            return base.Channel.GetMD5Async(Source);
        }
        
        public System.Threading.Tasks.Task<string> Get_Vlt_NoAsync()
        {
            return base.Channel.Get_Vlt_NoAsync();
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_CityAsync()
        {
            return base.Channel.Get_CityAsync();
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_City_PlaceAsync(string meb_zip_add_no)
        {
            return base.Channel.Get_City_PlaceAsync(meb_zip_add_no);
        }
        
        public System.Threading.Tasks.Task<string> Get_City_Place_ZipAsync(string meb_zip_add_no)
        {
            return base.Channel.Get_City_Place_ZipAsync(meb_zip_add_no);
        }
        
        public System.Threading.Tasks.Task<EipService.Get_City_Place_By_ZipResponseGet_City_Place_By_ZipResult> Get_City_Place_By_ZipAsync(string MEB_ZIP_ADD_zip)
        {
            return base.Channel.Get_City_Place_By_ZipAsync(MEB_ZIP_ADD_zip);
        }
        
        public System.Threading.Tasks.Task<string> Add_Vlt_Basic_DataAsync(
                    string bel_no, 
                    string ble_type, 
                    string userid, 
                    string password, 
                    string pass_question, 
                    string pass_answer, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno)
        {
            return base.Channel.Add_Vlt_Basic_DataAsync(bel_no, ble_type, userid, password, pass_question, pass_answer, username, email, telno, countyname, cityname, zipcode, address, birthday, gender, contactperson, cptelno);
        }
        
        public System.Threading.Tasks.Task<string> Update_Vlt_Basic_DataAsync(
                    string bel_no, 
                    string ble_type, 
                    string userid, 
                    string pass_question, 
                    string pass_answer, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno)
        {
            return base.Channel.Update_Vlt_Basic_DataAsync(bel_no, ble_type, userid, pass_question, pass_answer, username, email, telno, countyname, cityname, zipcode, address, birthday, gender, contactperson, cptelno);
        }
        
        public System.Threading.Tasks.Task<string> Update_Vlt_Basic_Data_PerAsync(
                    string bel_no, 
                    string ble_type, 
                    string username, 
                    string email, 
                    string telno, 
                    string countyname, 
                    string cityname, 
                    string zipcode, 
                    string address, 
                    string birthday, 
                    string gender, 
                    string contactperson, 
                    string cptelno, 
                    string job, 
                    string school, 
                    string icno)
        {
            return base.Channel.Update_Vlt_Basic_Data_PerAsync(bel_no, ble_type, username, email, telno, countyname, cityname, zipcode, address, birthday, gender, contactperson, cptelno, job, school, icno);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_Basic_DataAsync(string bel_no)
        {
            return base.Channel.Get_Vlt_Basic_DataAsync(bel_no);
        }
        
        public System.Threading.Tasks.Task<string> Vlt_LoginAsync(string userid, string password)
        {
            return base.Channel.Vlt_LoginAsync(userid, password);
        }
        
        public System.Threading.Tasks.Task<string> Get_Userid_CountAsync(string userid)
        {
            return base.Channel.Get_Userid_CountAsync(userid);
        }
        
        public System.Threading.Tasks.Task<string> Get_Userid_Count_ByBlenoAsync(string bel_no, string userid)
        {
            return base.Channel.Get_Userid_Count_ByBlenoAsync(bel_no, userid);
        }
        
        public System.Threading.Tasks.Task<string> Get_BelNo_ByQuestionAsync(string userid, string email, string pass_question, string pass_answer)
        {
            return base.Channel.Get_BelNo_ByQuestionAsync(userid, email, pass_question, pass_answer);
        }
        
        public System.Threading.Tasks.Task<string> Update_Vlt_PasswordAsync(string bel_no, string password)
        {
            return base.Channel.Update_Vlt_PasswordAsync(bel_no, password);
        }
        
        public System.Threading.Tasks.Task<string> Send_mailAsync(string ls_from, string ls_fname, string ls_to, string ls_toname, string ls_mserver, string ls_subject, string ls_body)
        {
            return base.Channel.Send_mailAsync(ls_from, ls_fname, ls_to, ls_toname, ls_mserver, ls_subject, ls_body);
        }
        
        public System.Threading.Tasks.Task<string> Send_mail_1Async(string ls_from, string ls_fname, string ls_to, string ls_toname, string ls_mserver, string ls_subject, string ls_body)
        {
            return base.Channel.Send_mail_1Async(ls_from, ls_fname, ls_to, ls_toname, ls_mserver, ls_subject, ls_body);
        }
        
        public System.Threading.Tasks.Task<string> Send_Mail_3Async(string ls_to, string ls_to_name, string ls_f_name, string ls_subject, string ls_body)
        {
            return base.Channel.Send_Mail_3Async(ls_to, ls_to_name, ls_f_name, ls_subject, ls_body);
        }
        
        public System.Threading.Tasks.Task<string> GetPageAsync(string p_url)
        {
            return base.Channel.GetPageAsync(p_url);
        }
        
        public System.Threading.Tasks.Task<string> Get_PilNoAsync()
        {
            return base.Channel.Get_PilNoAsync();
        }
        
        public System.Threading.Tasks.Task<string> Add_PilgrimageAsync(
                    string pil_no, 
                    string bel_no, 
                    string pil_type, 
                    string pil_mem_type, 
                    string pil_stay, 
                    string pil_date, 
                    string pil_num, 
                    string pil_stay_man_num, 
                    string pil_stay_woman_num, 
                    string pil_eat_num, 
                    string pil_eat_box, 
                    string bel_type, 
                    string pil_leader, 
                    string pil_htel, 
                    string pil_otel, 
                    string pil_mtel, 
                    string pil_state, 
                    string ls_dsql)
        {
            return base.Channel.Add_PilgrimageAsync(pil_no, bel_no, pil_type, pil_mem_type, pil_stay, pil_date, pil_num, pil_stay_man_num, pil_stay_woman_num, pil_eat_num, pil_eat_box, bel_type, pil_leader, pil_htel, pil_otel, pil_mtel, pil_state, ls_dsql);
        }
        
        public System.Threading.Tasks.Task<string> Update_PilAsync(
                    string pil_no, 
                    string bel_no, 
                    string pil_type, 
                    string pil_mem_type, 
                    string pil_stay, 
                    string pil_date, 
                    string pil_num, 
                    string pil_stay_man_num, 
                    string pil_stay_woman_num, 
                    string pil_eat_num, 
                    string pil_eat_box, 
                    string bel_type, 
                    string pil_leader, 
                    string pil_htel, 
                    string pil_otel, 
                    string pil_mtel, 
                    string pil_mass, 
                    string pil_mass_mtel, 
                    string pil_state, 
                    string user_no, 
                    string user_rec, 
                    string ls_dsql)
        {
            return base.Channel.Update_PilAsync(pil_no, bel_no, pil_type, pil_mem_type, pil_stay, pil_date, pil_num, pil_stay_man_num, pil_stay_woman_num, pil_eat_num, pil_eat_box, bel_type, pil_leader, pil_htel, pil_otel, pil_mtel, pil_mass, pil_mass_mtel, pil_state, user_no, user_rec, ls_dsql);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_PilgrimageAsync(string ser_sql)
        {
            return base.Channel.Get_PilgrimageAsync(ser_sql);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Pil_MemAsync(string pil_no)
        {
            return base.Channel.Get_Pil_MemAsync(pil_no);
        }
        
        public System.Threading.Tasks.Task<string> Add_Pil_MemAsync(string pil_no, string seq_no, string pil_cname, string pil_sex, string pil_tel, string pil_addr, string pil_email, string pil_type, string pil_meno)
        {
            return base.Channel.Add_Pil_MemAsync(pil_no, seq_no, pil_cname, pil_sex, pil_tel, pil_addr, pil_email, pil_type, pil_meno);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Item_SourceAsync(string item_type)
        {
            return base.Channel.Get_Item_SourceAsync(item_type);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_SkillAsync(string bel_no)
        {
            return base.Channel.Get_Vlt_SkillAsync(bel_no);
        }
        
        public System.Threading.Tasks.Task<string> Get_Vlt_Skill_By_Item_NoAsync(string bel_no, string item_no)
        {
            return base.Channel.Get_Vlt_Skill_By_Item_NoAsync(bel_no, item_no);
        }
        
        public System.Threading.Tasks.Task<string> Add_Vlt_SkillAsync(string bel_no, string item_no)
        {
            return base.Channel.Add_Vlt_SkillAsync(bel_no, item_no);
        }
        
        public System.Threading.Tasks.Task<string> Del_Vlt_SkillAsync(string bel_no, string item_no)
        {
            return base.Channel.Del_Vlt_SkillAsync(bel_no, item_no);
        }
        
        public System.Threading.Tasks.Task<string> Add_Vlt_TypeAsync(string bel_no, string mem_type)
        {
            return base.Channel.Add_Vlt_TypeAsync(bel_no, mem_type);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Vlt_TypeAsync(string bel_no)
        {
            return base.Channel.Get_Vlt_TypeAsync(bel_no);
        }
        
        public System.Threading.Tasks.Task<string> Add_Mem_AskAsync(string qu_no, string bel_no, string ask_title, string ask_content)
        {
            return base.Channel.Add_Mem_AskAsync(qu_no, bel_no, ask_title, ask_content);
        }
        
        public System.Threading.Tasks.Task<string> Update_Mem_AskAsync(string ask_no, string res_user_no, string res_content)
        {
            return base.Channel.Update_Mem_AskAsync(ask_no, res_user_no, res_content);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_Bel_AskAsync(string bel_no)
        {
            return base.Channel.Get_Bel_AskAsync(bel_no);
        }
        
        public System.Threading.Tasks.Task<EipService.ArrayOfXElement> Get_All_Bel_AskAsync(string Sql)
        {
            return base.Channel.Get_All_Bel_AskAsync(Sql);
        }
        
        public System.Threading.Tasks.Task<string> Add_tbMessageInform1Async(string SEQNo, string Memo1, string TransactionAmount, string TransactionDate, string TransactionTime)
        {
            return base.Channel.Add_tbMessageInform1Async(SEQNo, Memo1, TransactionAmount, TransactionDate, TransactionTime);
        }
        
        public System.Threading.Tasks.Task<string> getRandomValidateAsync(int len)
        {
            return base.Channel.getRandomValidateAsync(len);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_FGS_VLTSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_FGS_VLTSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_FGS_VLTSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.20.253.88:82/WS_FGS/WS_FGS_VLT.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_FGS_VLTSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.20.253.88:82/WS_FGS/WS_FGS_VLT.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_FGS_VLTSoap,
            
            WS_FGS_VLTSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
